import type { Metadata } from "next";
import { Raleway, Racing_Sans_One } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { cn } from "@/lib/utils";

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

const racingSansOne = Racing_Sans_One({
  variable: "--font-racing-sans-one",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Foso",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "bg-[#F9FBFC]",
          raleway.className,
          racingSansOne.variable
        )}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
